### ISSUE TITLE
RFI Removal

### ISSUE THREAD

**Issue by kevinawilson** [0xCoto/Virgo#15]
The documentation states that you can remove RFI channels from the ploy by providing a list that includes the high and low frequencies of the channels with RFI. Is it possible to block multiple instances of RFI this way? I've tried passing a list with multiple highs and lows and a list of lists, but neither worked.

Any help would be appreciated.

**Comment by 0xCoto** [comment]
It's not possible; you can also mask out one range of channels, but I completely understand the need for such feature.

I haven't gotten to this yet due to my time being a bit limited, but I have an idea of how it could be done and what the user would have to input instead of a single two-element list.

(If you're familiar with Python and would like to see this implemented sooner, you are more than welcome to submit a pull request of course!)

**Comment by kevinawilson** [comment]
I'm going to take a stab at allowing multiple sets of frequencies to be removed.

The code as it stands expects a two-element list for the rfi parameter. I suggest switching to a list of tuples, with each tuple consisting of a low and high frequency for the channels to filter. I can then iterate through all the items in the list and remove them from the waterfall.

If you want to maintain backward compatibility, I can think of two options. The simpler one is to leave the existing parameter as it is and create another parameter called something like rfi_multiple that could be used for multiple channels. This would allow people to continue using rfi without needing to update their scripts. The other option would be to keep using just rfi and handle it differently depending on whether the user passes a list of two integers or a list of tuples.

Thoughts?

**Comment by 0xCoto** [comment]
Yeah, that's more or less what I had in mind. I don't consider backwards compatibility a big deal given the only change for a single range is to replace [] with (), so feel free to give it a shot!

**Comment by kevinawilson** [comment]
I've written the code and tested it, and it works well. I tried to push it as a branch, but I was not authorized.

How would you prefer I upload the code so you can test it? I'm happy to cut and paste it here if you would like to add it manually.

**Comment by 0xCoto** [comment]
You can fork the repository, apply the changes and submit a pull request.

**Comment by 0xCoto** [comment]
Resolved by #17.
