### ISSUE TITLE
VLSR

### ISSUE THREAD

**Issue by kevinawilson** [0xCoto/Virgo#18]
I'm working on the VLSR transform. I'll provide details when I can. But I wanted to ask about the array of arrays that is loaded from the observation.dat file for plot(). What does each of the individual arrays represent? Is it storing all of the values that are taken during the iteration observation? If so, what is the structure of the array? Does each array represent all the values for one frequency, or does each array represent one reading of all the frequencies, with the next array representing the next reading and so on?

The SpectralCoord class in astropy takes a range of readings and adjusts them so that both the target and the observer are in the same frame of reference (usually ICSR). The results can then be transformed into the LSR.

Also, what is the unit of the stored value? Is it dB, S/N, or something else?

**Comment by 0xCoto** [comment]
The `waterfall` is structured like this:
![image](https://user-images.githubusercontent.com/25392776/124362542-34643e80-dc3e-11eb-9668-9226eceeac77.png)

(where `Z` used to express the `waterfall`, `Zmean` -> `avg_spectrum` (averaged (uncalibrated) spectrum) and `W`-> `power` (power vs time))

The waterfall includes all information post-FFT: the relative power as a function of frequency and as a function of time. As the observation is running (data acquisition), GNU Radio appends a new row at the bottom. So, each row represents an "instantaneous-ish" spectrum.

The power unit is arbitrary ("relative power" or "counts") and depends on the SDR, gain etc. dB can be enabled and automatically rescaled with `dB=True`, but this should not be confused with dBm (decibels relative to 1 mW) which is an absolute scale. S/N only pops up when the spectrum is calibrated and makes sense to use the "noise" segment of the spectrum (the flat region, i.e. when passband shape has been corrected to take the standard deviation for the noise level, with e.g. the HI signal masked).

I believe you won't need to pay too much attention to the structure of `waterfall` for VLSR corrections though (unless you're asking out of general curiosity). I think the only thing that has to be adjusted is the secondary X-axis of the averaged spectrum and (inherently) the calibrated spectrum, indicating velocity.

**Comment by kevinawilson** [comment]
In virgo.py line 544, you convert epoch time to mjd by dividing the epoch time by 86400, which gives the number of days. You then add 40587. What does this number represent? It seems to add about 111 years to the date.

I've been able to account for VLSR in the plot. Right now I'm trying to decide how to store galactic lat/long and observer location, as both of these are needed to convert to VLSR. I will probably save them in the header files so they can be retrieved later.

**Comment by 0xCoto** [comment]
I'd have to search where exactly I got these numbers from, but I just checked and the calculation is correct. E.g.
`python -c "import time;print(time.time())"` returns `1625836986.22`, and plugging this number [here](http://www.csgnetwork.com/julianmodifdateconv.html) gives `07-09-2021`, so it looks correct.

**Comment by 0xCoto** [comment]
Kinda relevant: http://www.sp.ph.ic.ac.uk/csc-web/MJD/MJDtime.htm

> Note that MJD for 1 Jan 1970 is 40587 (used for the Unix start epoch) and MJD for 1 Jan 2000 is 51544 (used by QSAS internally).
