### ISSUE TITLE
virgo.simulate does not return the LAB data

### ISSUE THREAD

**Issue by davewyers** [0xCoto/Virgo#28]
When running the virgo.simulate function it returns a PNG plot but it contains no LAB line.

The All Sky map is being returned correctly.

gal_l, gal_b = virgo.galactic(RA,DEC)
    print ('Galactic l = '+str(gal_l))
    print ('Galactic b = '+str(gal_b))
    virgo.simulate(gal_l, gal_b, beamwidth, -400, 400, prefix+'_simulate.png')

![image](https://user-images.githubusercontent.com/8073328/184293641-e1c83a24-064b-4afa-bfaa-c52a3cacf47e.png)

![image](https://user-images.githubusercontent.com/8073328/184293772-778a107d-23d8-4ab7-9551-e72ed3d13f54.png)

**Comment by 0xCoto** [comment]
As far as I know, the server (from which the data is being retrieved) has been down lately (see discussion here: https://groups.google.com/g/sara-list/c/YYUmwDT0yWk) - I believe it should be up in the next few days (it doesn't go down too often). To monitor whether the page is up or not: https://www.astro.uni-bonn.de/hisurvey/euhou/LABprofile/

**Comment by davewyers** [comment]
The web site is back up now seeing result 
![image](https://user-images.githubusercontent.com/8073328/185278578-6a3d41d9-269c-49da-9773-5c65e73f84cd.png)
