### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by Niemand112233** [0xCoto/Virgo#3]
Hi,
may you give some install instructions for all dependencies?
I'm trying to get it running for hours, but I get stuck in the installation of osmosdr. In addition, the top_block.py can't find gnuradio since it is still running with Python 2.7, while gnuradio is using python3.

I really would like to use your software but I can't get it up and running.

**Comment by 0xCoto** [comment]
I would suggest using GNU Radio with Python 2.7 if possible, since that’s the version VIRGO is based on.

How are you trying to install osmosdr? Are you on Windows or Linux? Do you see an RTL-SDR Source block perhaps?

**Comment by Niemand112233** [comment]
I have now everything installed, but I get the error in the "top_block.py" that it can't import gnuradio. "No module named gnuradio".

**Comment by 0xCoto** [comment]
Are you on Windows, Linux or OS X? If you don’t want to install GNU Radio for Python 2.7, you might have luck running `observe.py` with version 2 and modify it to call `top_block.py` with Python 3 with the help of `os.system()` for example.

**Comment by Niemand112233** [comment]
I'm running Linux. 
I changed a bit. Do you want to review it? It looks like to work now, except the plot_hi.py. But this could be because I don't have a SDR connected.

**Comment by 0xCoto** [comment]
Sure, feel free to share the code and I'll take a look. If you can get `plot.py` to work, `plot_hi.py` should also work by the same logic. Perhaps something worth noting is that the difference between `plot.py` and `plot_hi.py` is the spectrum calibration functionality: `plot_hi.py` tries to load an `offXXXX.dat` file, so you need to have that file available in the same directory for the script to work. If you can get `observe.py` (and `top_block.py` with `plot.py`) to work with your SDR, you should be able to manage `plot_hi.py` as well.

**Comment by Niemand112233** [comment]
I'm struggling right now with the error "plot_hi.py: error: the following arguments are required: freq, samp_rate, nchan, nbin". Do you have an idea how to solve this?

**Comment by 0xCoto** [comment]
What command did you execute (so I can see the parameter used for each argument)?

**Comment by Niemand112233** [comment]
This is my observe.py:
`import os
import sys
import datetime
from time import sleep
from subprocess import call

print('\n======================================================================================')
sleep(0.3)
print('VIRGO: An easy-to-use spectrometer & radiometer for Radio Astronomy based on GNU Radio')
sleep(0.3)
print('======================================================================================\n')
sleep(1)
print('[*] Please enter your desired observation parameters...\n')
sleep(0.5)

#Input observation parameters
f_center = str(input('Center frequency [MHz]: '))
f_center = str(float(f_center)*10**6)
bandwidth = str(input('Bandwidth [MHz]: '))
bandwidth = str(float(bandwidth)*10**6)
channels = str(input('Number of channels (FFT size): '))
t_int = str(input('Integration time per FFT sample [sec]: '))
nbins = str(int(float(t_int) * float(bandwidth)/float(channels)))
duration = str(input('Observing duration [sec]: '))

#Calibration option
cal = str(raw_input('\nWould you like to produce a calibrated spectrum at the end of your observation (requires off_nchan.dat calibration reference file in directory)? [y/N]: '))
yes = {'y', 'ye', 'yes'}
if cal.lower() in yes:
    cal = True
else:
    cal = False

schedule_duration = str(input('Start observation in [sec]: '))
if schedule_duration == '':
    schedule_duration = '0'
sleep(float(schedule_duration))
if schedule_duration != '0':
    print('\nThe observation will begin in '+schedule_duration+' sec automatically. Please wait...\n')

#Delete pre-existing observation.dat & plot.png files
try:
    os.remove('observation.dat')
    os.remove('plot.png')
except OSError:
    pass

#Note current datetime
currentDT = datetime.datetime.now()
obsDT = currentDT.strftime('%Y-%m-%d %H:%M:%S')
print('\n[+] Starting observation at ' + obsDT + ' (local computer time)...')

#Execute top_block.py with parameters
sys.argv = ['top_block.py', '--c-freq='+f_center, '--samp-rate='+bandwidth, '--nchan='+channels, '--nbin='+nbins, '--obs-time='+duration]
exit_code = call ("python3 top_block.py", shell=True)
print('[!] Observation finished! Plotting data...')

#Execute plotter
if cal:
    sys.argv = ['plot_hi.py', 'freq='+f_center, 'samp_rate='+bandwidth, 'nchan='+channels, 'nbin='+nbins]
    exit_code = call ("python3 plot_hi.py", shell=True)
else:
    sys.argv = ['plot.py', 'freq='+f_center, 'samp_rate='+bandwidth, 'nchan='+channels, 'nbin='+nbins]
    exit_code = call ("python3 plot.py", shell=True)

print('\n======================================================================================')
print('[+] The observation data has been plotted and saved as plot.png.')
print('======================================================================================')
`

Then I'm starting it with "python observer.py" and I insert:
Freq: 1420 MHz
Bandwith: 20 Mhz
FFT: 1000
Integration: 5 sec
Duration: 10 sec (just for testing)
then yes for the calibrated spectrum.
start observation in 1 sec.

Then the software starts but throws the mentioned error for plot_hi.py. If I say "no" for calibrated spectrum, I'll get the same error just for plot.py.

**Comment by 0xCoto** [comment]
Can you try with 2^n FFT channels instead? E.g. 1024 or 2048? Also, does your SDR support 20 MHz of instantaneous bandwidth? The RTL-SDR supports up to 3.2 MHz.

**Comment by 0xCoto** [comment]
I assume this issue is resolved, so I'm closing it.
