### ISSUE TITLE
Airpsy mini GNU Radio crash

### ISSUE THREAD

**Issue by jobgeheniau** [0xCoto/Virgo#8]
It seems that Airspy Mini does crash GNU radio on Windows 10 while AIRPSY says that it should work with GNU Radio. RTLSDR no problem, Airspy Mini Problem.

**Comment by awasisto** [comment]
Have you installed [libairspy](https://github.com/airspy/airspyone_host)? gr-osmosdr needs libairspy to use an Airspy device

**Comment by 0xCoto** [comment]
@awasisto - thanks for your input. This link was found, but the instructions aren't quite clear. GNU Radio 3.9 has been installed with conda on the Windows machine, but do you need to get Visual Studio to get libairspy installed?

And how exactly do you installed the "prerequisites for mingw", is that also handled by VS?

**Comment by jobgeheniau** [comment]
Nope, No idea how….

**Comment by awasisto** [comment]
@0xCoto I haven't tried to install it on Windows. On Linux, I can install gr-osmosdr with Airspy support by [installing libairspy from source](https://github.com/airspy/airspyone_host#how-to-build-the-host-software-on-linux) first, then [install gr-osmosdr from source](https://osmocom.org/projects/gr-osmosdr/wiki). If the libairspy is installed, "AIRSPY Receiver" will be listed under "Gnuradio enabled components" when installing gr-osmosdr

```
-- ######################################################
-- # Gnuradio enabled components                         
-- ######################################################
--   * Python support
--   * IQ File Source & Sink
--   * RTLSDR TCP Client
--   * RFSPACE Receivers
--   * AIRSPY Receiver      <------
--   * Red Pitaya SDR
-- 
-- ######################################################
-- # Gnuradio disabled components                        
-- ######################################################
--   * Osmocom IQ Imbalance Correction
--   * FUNcube Dongle
--   * Osmocom RTLSDR
--   * Ettus USRP Devices
--   * HackRF & rad1o Badge
--   * nuand bladeRF
--   * AIRSPY HF+ Receiver
--   * SoapySDR support
--   * FreeSRP support
--   * XTRX SDR
```

After installation, the osmocom source block should work with an Airspy device. I can't confirm it though. I don't have the device

**Comment by jobgeheniau** [comment]
He is trying to install it on my windows laptop. I hope he will succeed with your new information. Thanks.
